# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\"\x1b\n\nDL_request\x12\r\n\x05state\x18\x01 \x01(\x05\"/\n\x0b\x44L_response\x12\x0f\n\x07x_train\x18\x01 \x01(\x0c\x12\x0f\n\x07y_train\x18\x02 \x01(\x0c\x32\x34\n\nlayer2_out\x12&\n\x07request\x12\x0b.DL_request\x1a\x0c.DL_response\"\x00\x62\x06proto3'
)




_DL_REQUEST = _descriptor.Descriptor(
  name='DL_request',
  full_name='DL_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='DL_request.state', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=44,
)


_DL_RESPONSE = _descriptor.Descriptor(
  name='DL_response',
  full_name='DL_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_train', full_name='DL_response.x_train', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y_train', full_name='DL_response.y_train', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['DL_request'] = _DL_REQUEST
DESCRIPTOR.message_types_by_name['DL_response'] = _DL_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DL_request = _reflection.GeneratedProtocolMessageType('DL_request', (_message.Message,), {
  'DESCRIPTOR' : _DL_REQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:DL_request)
  })
_sym_db.RegisterMessage(DL_request)

DL_response = _reflection.GeneratedProtocolMessageType('DL_response', (_message.Message,), {
  'DESCRIPTOR' : _DL_RESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:DL_response)
  })
_sym_db.RegisterMessage(DL_response)



_LAYER2_OUT = _descriptor.ServiceDescriptor(
  name='layer2_out',
  full_name='layer2_out',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=95,
  serialized_end=147,
  methods=[
  _descriptor.MethodDescriptor(
    name='request',
    full_name='layer2_out.request',
    index=0,
    containing_service=None,
    input_type=_DL_REQUEST,
    output_type=_DL_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LAYER2_OUT)

DESCRIPTOR.services_by_name['layer2_out'] = _LAYER2_OUT

# @@protoc_insertion_point(module_scope)
